### ISSUE TITLE
Question: Naming convention

### ISSUE THREAD

**Issue by varholak-peter** [developer239/linters#20]
<img width="896" alt="Screenshot 2021-01-18 at 18 02 34" src="https://user-images.githubusercontent.com/19926448/104944533-a6f6a000-59b7-11eb-8a96-ae57438db832.png">

I don't think the regex `/((^T[A-Z][a-zA-Z]{2,}))+$/u` does what you want as the `(())` and `+` are useless.

I would propose `/^T[A-Z][a-zA-Z]+$/u` to allow `TId` or if you want to have `T` followed by minimum 3 other characters then `/^T[A-Z][a-zA-Z]{2,}$/u`. (I would still prefer the first one as it aligns better with the `id-length` rule.)

**Comment by developer239** [comment]
Aah Naming Convention, my old nemesis teamed up on me with Regex. 😄 I will fix it this weekend.

**Comment by developer239** [comment]
@varholak-peter  ✅ 🙌

**Comment by varholak-peter** [comment]
@developer239 I recommend using "Closes #20" in the PR including this change so it auto-closes the issue and also links it properly for future reference. 🙃
